apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: personal-eks-karpenter
spec:
  instanceProfile: "personal-eks-cluster"
  amiFamily: "AL2023"
  amiSelectorTerms:
  - id: ami-02382489c95ee1382
  securityGroupSelectorTerms:
  - id: sg-051bcdb68ac6e2c8e
  subnetSelectorTerms:
  - id: subnet-022a7aefa8353e94a2
  - id: subnet-04e439f62b375bd90
  - id: subnet-0ff77d81cd7c21339
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: personal-eks-karpenter
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
  template:
    metadata:
      labels:
        workload: "etc"  
    spec:
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:   
          - t3

        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
          - micro
          - small

        - key: karpenter.sh/capacity-type
          operator: In
          values:
          - "on-demand"
    
        - key: "topology.kubernetes.io/zone" 
          operator: In
          values:
          - "us-east-1a"
          - "us-east-1b"
          - "us-east-1c"          
          
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: personal-eks-karpenter
